"""
train_lora_sft.py

LoRA supervised fine-tuning for the MOSAIC-QC method-selection specialists,
over the SFT data already generated by generate_sft.py (jsonl/sft_{cell}.jsonl
+ jsonl/sft_val_{cell}.jsonl). Trains one LoRA adapter per specialist cell:

    organic_general   -- organic DFT (+ CCSD/MP2 organic records)
    organic_TDDFT     -- organic TDDFT
    metal_general     -- TM/heavy DFT + TDDFT + CCSD/MP2 metal records
    (TM_general, heavy_general, highlevel_SP also present as legacy/analysis
     cells -- included for completeness, not part of the 3-cell architecture)

Base model per the design doc (discussion_draft_0622.md, Section 5):
"Llama-3.1-8B or equivalent available on NII H200 cluster." Any HF causal LM
with a working chat template works (Llama-3.1-Instruct, Qwen2.5-Instruct,
Mistral-Instruct, ...) -- the masking logic below reads the template rather
than assuming a specific model's special tokens.

Training objective: standard causal LM loss, masked to the assistant's JSON
completion only (system+user tokens contribute zero loss). This is done by
rendering the prompt (everything up to and including the assistant header)
and the full conversation through the SAME tokenizer call, then diffing
token-index lengths -- verified to give an exact token-level prefix match
across chat-template models (see commit notes / session log), so it doesn't
hardcode any model's special-token spelling.

Evaluation (post-training, per dataset_manual.md's acceptance criterion):
generates completions for every validation example and reports the
functional+basis exact-match rate -- the checklist's target is >=80%.
Cells with an empty val file skip evaluation with a warning rather than
failing (none of the 3 main cells are empty as of this corpus snapshot,
after fixing tmQM's upload_id clustering -- see merge_methods.py).

First-step scope: --cell phase1 trains only organic_general + metal_general
(organic_TDDFT deferred). Use --cell all/main once phase1 results are in.

Requirements (see requirements.txt next to this file):
    torch (install the CUDA build matching your cluster first, see
           https://pytorch.org/get-started/locally/)
    transformers>=4.44
    peft>=0.12
    datasets>=2.19
    accelerate>=0.33
    bitsandbytes>=0.43   (only needed for --load-in-4bit / QLoRA)

Usage
-----
  # Recommended first step: organic_general + metal_general only
  # (bf16, no quantization -- fine on an H200):
  python train_lora_sft.py --cell phase1

  # Single cell:
  python train_lora_sft.py --cell organic_general

  # All cells including organic_TDDFT and the legacy/analysis ones:
  python train_lora_sft.py --cell all

  # QLoRA (4-bit) if running on a smaller/shared GPU:
  python train_lora_sft.py --cell metal_general --load-in-4bit

  # Different base model:
  python train_lora_sft.py --cell organic_general \
      --base-model Qwen/Qwen2.5-7B-Instruct

Output: LoRA adapter weights + training_config.json + eval_report.json under
  lora_output/{cell}/
"""

from __future__ import annotations

import argparse
import json
import os
import random
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

import torch
from torch.utils.data import Dataset
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    Trainer,
    TrainingArguments,
)
from peft import LoraConfig, PeftModel, get_peft_model, prepare_model_for_kbit_training

BASE_DIR = Path(__file__).resolve().parent
DEFAULT_DATA_DIR = BASE_DIR / "jsonl"
DEFAULT_OUTPUT_DIR = BASE_DIR / "lora_output"

PHASE1_CELLS = ["organic_general", "metal_general"]
MAIN_CELLS = ["organic_general", "organic_TDDFT", "metal_general"]
ALL_CELLS = MAIN_CELLS + ["TM_general", "heavy_general", "highlevel_SP"]

DEFAULT_LORA_TARGET_MODULES = [
    "q_proj", "k_proj", "v_proj", "o_proj",
    "gate_proj", "up_proj", "down_proj",
]

PARAM_FIELDS = [
    "functional", "basis", "ri_approx", "aux_basis",
    "grid_level", "final_grid_level", "dispersion", "scf_convergence",
    "relativistic", "solvent_model", "solvent",
    "nroots", "casscf_nel", "casscf_norb", "cbs_scheme",
]


# ─── data loading ───────────────────────────────────────────────────────────

def load_jsonl(path: Path) -> list[dict]:
    if not path.exists():
        return []
    with path.open(encoding="utf-8") as f:
        return [json.loads(line) for line in f if line.strip()]


# ─── prompt/completion masking ──────────────────────────────────────────────

def encode_example(messages: list[dict], tokenizer, max_len: int) -> Optional[dict]:
    """
    Tokenize a full {system, user, assistant} conversation and mask every
    token except the assistant's completion (loss=-100 elsewhere).

    Works by rendering the conversation twice through the tokenizer's own
    chat template: once in full, once with the assistant turn dropped and
    add_generation_prompt=True (i.e. exactly the prompt the model would see
    at inference). The second is a token-level prefix of the first for every
    chat-template model checked (Llama-3.1, Qwen2.5) -- so the split point is
    just the prompt's token count, with no dependence on a specific model's
    special-token spelling.
    """
    if not messages or messages[-1]["role"] != "assistant":
        return None

    full_text   = tokenizer.apply_chat_template(messages, tokenize=False)
    prompt_text = tokenizer.apply_chat_template(messages[:-1], tokenize=False, add_generation_prompt=True)

    full_ids   = tokenizer(full_text,   add_special_tokens=False)["input_ids"]
    prompt_ids = tokenizer(prompt_text, add_special_tokens=False)["input_ids"]

    if full_ids[:len(prompt_ids)] != prompt_ids:
        # Chat template isn't prefix-stable for this model -- skip rather
        # than silently train on a misaligned mask.
        return None

    if len(full_ids) > max_len:
        full_ids = full_ids[:max_len]

    labels = list(full_ids)
    mask_len = min(len(prompt_ids), len(labels))
    for i in range(mask_len):
        labels[i] = -100
    if mask_len >= len(labels):
        return None  # completion got truncated away entirely

    return {
        "input_ids": full_ids,
        "attention_mask": [1] * len(full_ids),
        "labels": labels,
    }


class SFTDataset(Dataset):
    def __init__(self, records: list[dict], tokenizer, max_len: int):
        self.examples = []
        skipped = 0
        for r in records:
            ex = encode_example(r["messages"], tokenizer, max_len)
            if ex is None:
                skipped += 1
                continue
            self.examples.append(ex)
        if skipped:
            print(f"  [data] skipped {skipped}/{len(records)} records "
                  f"(prefix-mask mismatch or empty completion after truncation)")

    def __len__(self):
        return len(self.examples)

    def __getitem__(self, idx):
        return self.examples[idx]


@dataclass
class PadCollator:
    pad_token_id: int

    def __call__(self, batch: list[dict]) -> dict:
        max_len = max(len(ex["input_ids"]) for ex in batch)
        input_ids, attention_mask, labels = [], [], []
        for ex in batch:
            pad = max_len - len(ex["input_ids"])
            input_ids.append(ex["input_ids"] + [self.pad_token_id] * pad)
            attention_mask.append(ex["attention_mask"] + [0] * pad)
            labels.append(ex["labels"] + [-100] * pad)
        return {
            "input_ids": torch.tensor(input_ids, dtype=torch.long),
            "attention_mask": torch.tensor(attention_mask, dtype=torch.long),
            "labels": torch.tensor(labels, dtype=torch.long),
        }


# ─── model / LoRA setup ─────────────────────────────────────────────────────

def load_model_and_tokenizer(base_model: str, load_in_4bit: bool):
    tokenizer = AutoTokenizer.from_pretrained(base_model)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    quant_config = None
    if load_in_4bit:
        quant_config = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_compute_dtype=torch.bfloat16,
            bnb_4bit_quant_type="nf4",
            bnb_4bit_use_double_quant=True,
        )

    model = AutoModelForCausalLM.from_pretrained(
        base_model,
        torch_dtype=torch.bfloat16,
        quantization_config=quant_config,
        device_map="auto",
    )
    if load_in_4bit:
        model = prepare_model_for_kbit_training(model)
    return model, tokenizer


def attach_lora(model, r: int, alpha: int, dropout: float, target_modules: list[str]):
    config = LoraConfig(
        r=r,
        lora_alpha=alpha,
        lora_dropout=dropout,
        target_modules=target_modules,
        bias="none",
        task_type="CAUSAL_LM",
    )
    model = get_peft_model(model, config)
    model.print_trainable_parameters()
    return model


# ─── evaluation ──────────────────────────────────────────────────────────────

def _extract_json(text: str) -> Optional[dict]:
    """Best-effort: find the first {...} block and parse it."""
    start = text.find("{")
    end = text.rfind("}")
    if start == -1 or end == -1 or end < start:
        return None
    try:
        return json.loads(text[start:end + 1])
    except json.JSONDecodeError:
        return None


@torch.no_grad()
def evaluate_cell(model, tokenizer, val_records: list[dict], max_new_tokens: int) -> dict:
    model.eval()
    n = len(val_records)
    n_parsed = 0
    n_func_match = 0
    n_basis_match = 0
    n_both_match = 0
    samples = []

    for rec in val_records:
        messages = rec["messages"]
        gold = _extract_json(messages[-1]["content"]) or {}
        prompt_messages = messages[:-1]
        prompt_text = tokenizer.apply_chat_template(
            prompt_messages, tokenize=False, add_generation_prompt=True
        )
        inputs = tokenizer(prompt_text, return_tensors="pt", add_special_tokens=False).to(model.device)
        out = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            pad_token_id=tokenizer.pad_token_id,
        )
        completion = tokenizer.decode(out[0][inputs["input_ids"].shape[1]:], skip_special_tokens=True)
        pred = _extract_json(completion)

        if pred is not None:
            n_parsed += 1
            func_ok = pred.get("functional") == gold.get("functional")
            basis_ok = pred.get("basis") == gold.get("basis")
            n_func_match += func_ok
            n_basis_match += basis_ok
            n_both_match += (func_ok and basis_ok)

        if len(samples) < 5:
            samples.append({"prompt": prompt_messages[-1]["content"], "gold": gold,
                             "pred_raw": completion, "pred_parsed": pred})

    return {
        "n_val": n,
        "n_parsed": n_parsed,
        "parse_rate": round(n_parsed / n, 4) if n else 0.0,
        "functional_exact_match_rate": round(n_func_match / n, 4) if n else 0.0,
        "basis_exact_match_rate": round(n_basis_match / n, 4) if n else 0.0,
        "functional_and_basis_exact_match_rate": round(n_both_match / n, 4) if n else 0.0,
        "meets_80pct_target": (n_both_match / n) >= 0.80 if n else None,
        "samples": samples,
    }


# ─── per-cell training run ──────────────────────────────────────────────────

def train_one_cell(cell: str, args: argparse.Namespace) -> None:
    print(f"\n{'=' * 90}\nCell: {cell}\n{'=' * 90}")

    train_path = args.data_dir / f"sft_{cell}.jsonl"
    val_path   = args.data_dir / f"sft_val_{cell}.jsonl"
    train_records = load_jsonl(train_path)
    val_records   = load_jsonl(val_path)

    if not train_records:
        print(f"  [skip] no train file at {train_path}")
        return

    print(f"  train: {len(train_records)} records ({train_path})")
    print(f"  val:   {len(val_records)} records ({val_path})")

    out_dir = args.output_dir / cell
    out_dir.mkdir(parents=True, exist_ok=True)

    ckpt_dir = (args.checkpoint_dir / cell) if args.checkpoint_dir else (out_dir / "checkpoints")

    random.seed(args.seed)
    torch.manual_seed(args.seed)

    model, tokenizer = load_model_and_tokenizer(args.base_model, args.load_in_4bit)
    if args.gradient_checkpointing:
        model.gradient_checkpointing_enable()
        model.enable_input_require_grads()

    model = attach_lora(model, args.lora_r, args.lora_alpha, args.lora_dropout,
                         args.lora_target_modules)

    train_ds = SFTDataset(train_records, tokenizer, args.max_seq_len)
    collator = PadCollator(pad_token_id=tokenizer.pad_token_id)

    training_args = TrainingArguments(
        output_dir=str(ckpt_dir),
        num_train_epochs=args.epochs,
        per_device_train_batch_size=args.batch_size,
        gradient_accumulation_steps=args.grad_accum,
        learning_rate=args.lr,
        lr_scheduler_type="cosine",
        warmup_ratio=0.03,
        bf16=True,
        logging_steps=10,
        save_strategy="epoch",
        save_total_limit=1,
        report_to=[],
        seed=args.seed,
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_ds,
        data_collator=collator,
    )

    t0 = time.monotonic()
    trainer.train()
    duration_s = time.monotonic() - t0
    print(f"  training done in {duration_s:.0f}s")

    model.save_pretrained(str(out_dir))
    tokenizer.save_pretrained(str(out_dir))
    with (out_dir / "log_history.json").open("w", encoding="utf-8") as f:
        json.dump(trainer.state.log_history, f, indent=2)
    print(f"  adapter saved to {out_dir}")

    config_manifest = {
        "cell": cell,
        "base_model": args.base_model,
        "n_train": len(train_records),
        "n_train_used": len(train_ds),
        "n_val": len(val_records),
        "load_in_4bit": args.load_in_4bit,
        "lora_r": args.lora_r,
        "lora_alpha": args.lora_alpha,
        "lora_dropout": args.lora_dropout,
        "lora_target_modules": args.lora_target_modules,
        "epochs": args.epochs,
        "batch_size": args.batch_size,
        "grad_accum": args.grad_accum,
        "lr": args.lr,
        "max_seq_len": args.max_seq_len,
        "seed": args.seed,
        "duration_s": round(duration_s, 1),
        "timestamp_utc": time.strftime("%Y%m%dT%H%M%SZ", time.gmtime()),
    }
    with (out_dir / "training_config.json").open("w", encoding="utf-8") as f:
        json.dump(config_manifest, f, indent=2)

    if not val_records:
        print(f"  [eval] skipped -- {val_path} is empty (known gap for this cell as of "
              f"the current corpus snapshot; see dataset_manual.md).")
        return

    print(f"  [eval] generating completions for {len(val_records)} val examples...")
    report = evaluate_cell(model, tokenizer, val_records, args.eval_max_new_tokens)
    print(f"  [eval] parse_rate={report['parse_rate']:.1%}  "
          f"functional_match={report['functional_exact_match_rate']:.1%}  "
          f"basis_match={report['basis_exact_match_rate']:.1%}  "
          f"both_match={report['functional_and_basis_exact_match_rate']:.1%}  "
          f"(target >=80%: {'PASS' if report['meets_80pct_target'] else 'FAIL'})")

    with (out_dir / "eval_report.json").open("w", encoding="utf-8") as f:
        json.dump(report, f, indent=2)

    del model
    torch.cuda.empty_cache() if torch.cuda.is_available() else None


# ─── CLI ─────────────────────────────────────────────────────────────────────

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="LoRA SFT for MOSAIC-QC method-selection specialists")
    p.add_argument("--cell", default="phase1", choices=ALL_CELLS + ["all", "main", "phase1"],
                    help="Which specialist cell to train. 'phase1' (default, recommended "
                         "first step) = organic_general + metal_general only. 'main' = all "
                         "3 primary cells (adds organic_TDDFT). 'all' = every cell with a "
                         "train file, including legacy/analysis cells.")
    p.add_argument("--base-model", default="meta-llama/Llama-3.1-8B-Instruct",
                    help="HF model id or local path. Any causal LM with a working chat "
                         "template works (default per design doc: Llama-3.1-8B-Instruct).")
    p.add_argument("--data-dir", type=Path, default=DEFAULT_DATA_DIR)
    p.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    p.add_argument("--checkpoint-dir", type=Path, default=None,
                    help="Where the Trainer writes its full per-epoch checkpoints "
                         "(optimizer/scheduler/rng state, much bigger than the final "
                         "adapter). Point this at local compute-node disk (e.g. "
                         "$HF_HOME on the nii cluster) to avoid filling the shared "
                         "/home NFS quota -- found 2026-07-30: /home hit 100%% full "
                         "cluster-wide and silently killed a training run mid-epoch "
                         "with no Python traceback. Defaults to output-dir/{cell}/"
                         "checkpoints (the old, NFS-backed behavior) if unset. Only "
                         "the final adapter + log_history.json (loss curve) are ever "
                         "written to --output-dir, so it's fine for that to stay on "
                         "shared storage.")
    p.add_argument("--load-in-4bit", action="store_true",
                    help="QLoRA: quantize the base model to 4-bit (bitsandbytes). Use on "
                         "smaller/shared GPUs; not needed on a full H200 for an 8B model.")
    p.add_argument("--epochs", type=float, default=3.0)
    p.add_argument("--batch-size", type=int, default=4)
    p.add_argument("--grad-accum", type=int, default=4)
    p.add_argument("--lr", type=float, default=2e-4)
    p.add_argument("--max-seq-len", type=int, default=1024,
                    help="These prompts+completions are short (~100-300 tokens); 1024 "
                         "is generous headroom.")
    p.add_argument("--lora-r", type=int, default=16)
    p.add_argument("--lora-alpha", type=int, default=32)
    p.add_argument("--lora-dropout", type=float, default=0.05)
    p.add_argument("--lora-target-modules", type=lambda s: s.split(","),
                    default=DEFAULT_LORA_TARGET_MODULES,
                    help="Comma-separated module names, e.g. for an architecture that "
                         "doesn't use the Llama/Qwen/Mistral-style proj naming.")
    p.add_argument("--gradient-checkpointing", action="store_true", default=True)
    p.add_argument("--no-gradient-checkpointing", dest="gradient_checkpointing", action="store_false")
    p.add_argument("--eval-max-new-tokens", type=int, default=128)
    p.add_argument("--seed", type=int, default=0)
    return p.parse_args()


def main() -> None:
    args = parse_args()

    if args.cell == "all":
        cells = [c for c in ALL_CELLS if (args.data_dir / f"sft_{c}.jsonl").exists()]
    elif args.cell == "main":
        cells = MAIN_CELLS
    elif args.cell == "phase1":
        cells = PHASE1_CELLS
    else:
        cells = [args.cell]

    print(f"Base model: {args.base_model}")
    print(f"Cells to train: {cells}")
    print(f"CUDA available: {torch.cuda.is_available()}")
    if not torch.cuda.is_available():
        print("WARNING: no CUDA device visible. This script is meant to run on a GPU "
              "(the design doc targets an NII H200 node) -- it will be extremely slow "
              "or fail to fit an 8B model on CPU.")

    for cell in cells:
        train_one_cell(cell, args)


if __name__ == "__main__":
    main()
